### ISSUE TITLE
问一下引入库怎么引入？

### ISSUE THREAD

**Issue by note286** [freedom10086/Ruisi_Ios#1]
能具体说一下吗，我的水平也就是源码给我，我点一下编译到手机里而已

**Comment by freedom10086** [comment]
- [Kingfisher手动导入](https://github.com/onevcat/Kingfisher/wiki/Installation-Guide#user-content-manually)，见Manually章节
```
git submodule add https://github.com/onevcat/Kingfisher.git
```
把Kingfisher.xcodeproj拖到项目里面去
> Open the Kingfisher folder, and drag Kingfisher.xcodeproj into the file navigator of your app project, under your app project.
- Kanna导入，直接把整个项目clone
```
https://github.com/tid-kijyun/Kanna.git
```
再把Kanna.xcodeproj拖到工程里面去

**Comment by note286** [comment]
@freedom10086 非常感谢，已经成功安装了，美滋滋

**Comment by freedom10086** [comment]
已经切换到pod了，不用手动安装了
