### ISSUE TITLE
建议增加设置字号的功能

### ISSUE THREAD

**Issue by note286** [freedom10086/Ruisi_Ios#3]
我的手机把字体调节大了，所以RSapp的部分页面布局显着很拥挤，我觉得考虑不同字体的布局不如增加一个设置字号的功能更省事吧，建议可以设置不使用跟随系统的字号，可以自己设置标准的字号。
![img_0103](https://user-images.githubusercontent.com/16207292/37023953-8a79fe8a-2162-11e8-8741-37f0bedc65ee.jpg)
![img_0102](https://user-images.githubusercontent.com/16207292/37023954-8b5353ba-2162-11e8-85f5-2937e2232bef.PNG)
![img_0101](https://user-images.githubusercontent.com/16207292/37023957-8c590034-2162-11e8-9126-3bd0655d987c.PNG)

**Comment by freedom10086** [comment]
感谢反馈，这边我还没测试过，下几个版本会优化一下。
现在部分字体用的系统字体确实会出现这种情况。

**Comment by freedom10086** [comment]
已经修改不跟随系统字体大小，写成固定值了

**Comment by note286** [comment]
@freedom10086 非常感谢，坐等商店更新。
