### ISSUE TITLE
校园交易的展示列表标题增加求或者卖的显示

### ISSUE THREAD

**Issue by note286** [freedom10086/Ruisi_Ios#6]
建议增加在校园交易板块的列表展示部分，每个标题起码有个求或者卖的字样，最好有南北校区，为了节省空间可以简写啊，例如新卖，老求，老卖，新求，这样，应为好多人写标题连求都不写，比如说求英语听说，只写英语听说，看首页的标题啥也看不出来，我手里有一本想卖掉呢，点进去一看是出，就很浪费时间，不知道理解我的意思没有。

**Comment by freedom10086** [comment]
校园网环境下已实现，外网目前无法实现
